import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HookupLayout({ children }) {
  return (
    <div>
      <main>{children}</main>
    </div>
  );
}
